services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - PROJECT_NAME=${PROJECT_NAME}
      - MONGODB_URI=${MONGODB_URI}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - ELEVEN_LAB_API_KEY=${ELEVEN_LAB_API_KEY}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
    volumes:
      - .:/app
    depends_on:
      - postgres
      - mongo
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: infosec_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data:
  redis_data: